version: "2.1"

services:
  server-01:
    build: .
    image: groupcache-example:local
    ports:
      - "3001:3000"
    environment:
      PEERS_TYPE: "set"
      LOG_LEVEL: "debug"
      PEERS_PROTOCOL: "grpc"
      PEERS_SELF: "server-01:3001"
      PEERS_SET: "server-01:3001,server-02:3001,server-03:3001"
      LISTEN_ADDR_GRPC: ":3001"


  server-02:
    build: .
    image: groupcache-example:local
    ports:
      - "3002:3000"
    environment:
      PEERS_TYPE: "set"
      LOG_LEVEL: "debug"
      PEERS_PROTOCOL: "grpc"
      PEERS_SELF: "server-02:3001"
      PEERS_SET: "server-01:3001,server-02:3001,server-03:3001"
      LISTEN_ADDR_GRPC: ":3001"

  server-03:
    build: .
    image: groupcache-example:local
    ports:
      - "3003:3000"
    environment:
      PEERS_TYPE: "set"
      LOG_LEVEL: "debug"
      PEERS_PROTOCOL: "grpc"
      PEERS_SELF: "server-03:3001"
      PEERS_SET: "server-01:3001,server-02:3001,server-03:3001"
      LISTEN_ADDR_GRPC: ":3001"

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/00-proxy.conf:ro
    ports:
      - "8080:8080"
    links:
      - server-01
      - server-02
      - server-03
