---
apiVersion: v1
kind: Service
metadata:
  name: groupcache-svc
spec:
  type: NodePort
  selector:
    app: groupcache
  ports:
    - port: 3000
      nodePort: 30000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: groupcache-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupcache
  labels:
    app: groupcache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groupcache
  template:
    metadata:
      labels:
        app: groupcache
    spec:
      serviceAccountName: groupcache-sa
      containers:
        - name: groupcache-server
          image: groupcache-example:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: "api"
            - containerPort: 3001
              name: "grpc"
          env:
            - name: PEERS_TYPE
              value: "pods"
            - name: GUBERNATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GUBERNATOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GUBERNATOR_POD_PORT
              value: "3001"
            - name: GUBERNATOR_SELECTOR
              value: "app=groupcache"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_REQUESTS
              value: "true"
            - name: PPROF_ENABLED
              value: "true"
            - name: PEERS_PROTOCOL
              value: "grpc"
            - name: LISTEN_ADDR_GRPC
              value: ":3001"